state_abbreviation_dict = {
    "alabama": "AL",
    "alaska": "AK",
    "arizona": "AZ",
    "arkansas": "AR",
    "california": "CA",
    "colorado": "CO",
    "connecticut": "CT",
    "delaware": "DE",
    "florida": "FL",
    "georgia": "GA",
    "hawaii": "HI",
    "idaho": "ID",
    "illinois": "IL",
    "indiana": "IN",
    "iowa": "IA",
    "kansas": "KS",
    "kentucky": "KY",
    "louisiana": "LA",
    "maine": "ME",
    "maryland": "MD",
    "massachusetts": "MA",
    "michigan": "MI",
    "minnesota": "MN",
    "mississippi": "MS",
    "missouri": "MO",
    "montana": "MT",
    "nebraska": "NE",
    "nevada": "NV",
    "new hampshire": "NH",
    "new jersey": "NJ",
    "new mexico": "NM",
    "new york": "NY",
    "north carolina": "NC",
    "north dakota": "ND",
    "ohio": "OH",
    "oklahoma": "OK",
    "oregon": "OR",
    "pennsylvania": "PA",
    "rhode island": "RI",
    "south carolina": "SC",
    "south dakota": "SD",
    "tennessee": "TN",
    "texas": "TX",
    "utah": "UT",
    "vermont": "VT",
    "virginia": "VA",
    "washington": "WA",
    "west virginia": "WV",
    "wisconsin": "WI",
    "wyoming": "WY"
}

environmental_terms = [
    "air quality",
    "carbon emissions",
    "climate change",
    "conservation",
    "ecosystem",
    "endangered species",
    "environmental impact",
    "greenhouse gases",
    "hazardous waste",
    "pollution",
    "recycling",
    "sustainability",
    "water quality",
    "waste management",
    "renewable energy",
    "carbon footprint",
    "biodiversity",
    "deforestation",
    "wildlife protection",
    "natural resources",
    "carbon tax",
    "environmental justice",
    "climate mitigation",
    "climate adaptation",
    "soil erosion",
    "ecosystem restoration",
    "plastic pollution",
    "green energy",
    "sustainable development",
    "pollution control",
    "water conservation"
]
# columns: year, state, ratio of legislation, ratio of GDP